package org.vsa.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import org.vsa.api.Interrogation;
import org.vsa.api.VsaSystem;
import org.vsa.gui.listmodels.InterrogationListModel;
import org.vsa.gui.tasks.ClassifyTask;
import org.vsa.gui.tasks.GenerateArffTask;
import org.vsa.gui.tasks.SaveModelTask;
import org.vsa.gui.tasks.ShowExperimentSummaryTask;
import org.vsa.gui.tasks.ShowInterrogationDetailsTask;
import org.vsa.gui.tasks.ShowStressedInstancesDistribution;
import org.vsa.gui.tasks.ShowSummaryTask;
import org.vsa.gui.tasks.ShowUnstressedInstancesDistribution;

/**
 * MainWindow
 */
public class MainWindow extends JFrame {

    /**
     * vsaSystem
     */
    private final VsaSystem vsaSystem = new VsaSystem();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        // init components
        initComponents();

        // center this window
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        // set list model
        lbInterrogations.setModel(new InterrogationListModel(vsaSystem));
    }

    /**
     * @return the vsaSystem
     */
    public VsaSystem getVsaSystem() {
        return vsaSystem;
    }

    /**
     * getSelectedInterrogation
     *
     * @return
     */
    public Interrogation getSelectedInterrogation() {
        // get interrogation from list
        Interrogation interrogation = (Interrogation)lbInterrogations.getSelectedValue();

        // return value
        return interrogation;
    }

    public List<Object> getSelectedInterrogations() {
        return lbInterrogations.getSelectedValuesList();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbInterrogations = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuClassifyFile = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuAction = new javax.swing.JMenu();
        mnuSummary = new javax.swing.JMenuItem();
        mnuDetails = new javax.swing.JMenuItem();
        mnuClassify = new javax.swing.JMenuItem();
        mnuGenerateArff = new javax.swing.JMenuItem();
        generateModel = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuOpcjeWeka = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuStressedExperimentSummary = new javax.swing.JMenuItem();
        mnuDrawStressedDistribution = new javax.swing.JMenuItem();
        mnuDrawUnstressedDistribution = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VSA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Interrogation"));

        jScrollPane1.setViewportView(lbInterrogations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnuFile.setText("File");

        mnuClassifyFile.setText("Classify file");
        mnuClassifyFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClassifyFileActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClassifyFile);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuAction.setText("Action");

        mnuSummary.setText("Summary");
        mnuSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSummaryActionPerformed(evt);
            }
        });
        mnuAction.add(mnuSummary);

        mnuDetails.setText("Details");
        mnuDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetailsActionPerformed(evt);
            }
        });
        mnuAction.add(mnuDetails);

        mnuClassify.setText("Classify instance");
        mnuClassify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClassifyActionPerformed(evt);
            }
        });
        mnuAction.add(mnuClassify);

        mnuGenerateArff.setText("Generate Weka Arff file");
        mnuGenerateArff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerateArffActionPerformed(evt);
            }
        });
        mnuAction.add(mnuGenerateArff);

        generateModel.setText("Generate Weka model");
        generateModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateModelActionPerformed(evt);
            }
        });
        mnuAction.add(generateModel);

        jMenuBar1.add(mnuAction);

        jMenu1.setText("Options");

        MenuOpcjeWeka.setText("Options");
        MenuOpcjeWeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpcjeWekaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOpcjeWeka);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Experiment");

        mnuStressedExperimentSummary.setText("Show analysis results");
        mnuStressedExperimentSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStressedExperimentSummaryActionPerformed(evt);
            }
        });
        jMenu2.add(mnuStressedExperimentSummary);

        mnuDrawStressedDistribution.setText("Normal distribution of stressed voice");
        mnuDrawStressedDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDrawStressedDistributionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDrawStressedDistribution);

        mnuDrawUnstressedDistribution.setText("Normal distribution of unstressed voice");
        mnuDrawUnstressedDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDrawUnstressedDistributionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDrawUnstressedDistribution);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGenerateArffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerateArffActionPerformed
        GenerateArffTask task = new GenerateArffTask(this);
        task.execute();
    }//GEN-LAST:event_mnuGenerateArffActionPerformed

    private void mnuClassifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClassifyActionPerformed
        ClassifyTask task = new ClassifyTask(this);
        task.execute();
    }//GEN-LAST:event_mnuClassifyActionPerformed

    private void mnuDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetailsActionPerformed
        ShowInterrogationDetailsTask task = new ShowInterrogationDetailsTask(this);
        task.execute();
    }//GEN-LAST:event_mnuDetailsActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSummaryActionPerformed
        ShowSummaryTask task = new ShowSummaryTask(this);
        task.execute();
    }//GEN-LAST:event_mnuSummaryActionPerformed

    private void MenuOpcjeWekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpcjeWekaActionPerformed
        WekaOptions options = new WekaOptions(this);
        options.setVisible(true);
    }//GEN-LAST:event_MenuOpcjeWekaActionPerformed

    private void generateModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateModelActionPerformed
        SaveModelTask task = new SaveModelTask(this);
        task.execute();
    }//GEN-LAST:event_generateModelActionPerformed

    private void mnuClassifyFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClassifyFileActionPerformed
        FileChose fileChose = new FileChose(this);
        fileChose.setVisible(true);
    }//GEN-LAST:event_mnuClassifyFileActionPerformed

    private void mnuStressedExperimentSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStressedExperimentSummaryActionPerformed
        ShowExperimentSummaryTask task = new ShowExperimentSummaryTask(this);
        task.execute();
    }//GEN-LAST:event_mnuStressedExperimentSummaryActionPerformed

    private void mnuDrawStressedDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDrawStressedDistributionActionPerformed
        ShowStressedInstancesDistribution task = new ShowStressedInstancesDistribution(this);
        task.execute();
    }//GEN-LAST:event_mnuDrawStressedDistributionActionPerformed

    private void mnuDrawUnstressedDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDrawUnstressedDistributionActionPerformed
        ShowUnstressedInstancesDistribution task = new ShowUnstressedInstancesDistribution(this);
        task.execute();
    }//GEN-LAST:event_mnuDrawUnstressedDistributionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuOpcjeWeka;
    private javax.swing.JMenuItem generateModel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lbInterrogations;
    private javax.swing.JMenu mnuAction;
    private javax.swing.JMenuItem mnuClassify;
    private javax.swing.JMenuItem mnuClassifyFile;
    private javax.swing.JMenuItem mnuDetails;
    private javax.swing.JMenuItem mnuDrawStressedDistribution;
    private javax.swing.JMenuItem mnuDrawUnstressedDistribution;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuGenerateArff;
    private javax.swing.JMenuItem mnuStressedExperimentSummary;
    private javax.swing.JMenuItem mnuSummary;
    // End of variables declaration//GEN-END:variables
}
