package org.vsa.gui;

import javax.swing.JFrame;

/**
 * ProgressWindow
 */
public class ProgressWindow extends javax.swing.JDialog {

    /**
     * Creates new form ProgressWindow
     * 
     * @param parent
     */
    public ProgressWindow(JFrame parent) {
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * setMaxValue
     * 
     * @param max 
     */
    public void setMaxValue(int max) {
        this.progressBar.setMaximum(max);
    }

    /**
     * setValue
     * 
     * @param value 
     */
    public void setValue(int value) {
        this.progressBar.setValue(value);
    }

    /**
     * setIndeterminate
     * 
     * @param value 
     */
    public void setIndeterminate(boolean value) {
        this.progressBar.setIndeterminate(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
